name: 'Deploy to Agent Engine'
description: 'Deploy ADK agent code to Google Cloud Agent Engine'
author: 'Matthew Huie'
branding:
  icon: 'upload-cloud'
  color: 'white'
inputs:
  agent:
    description: 'Name of the agent to deploy'
    required: true
  project_id:
    description: 'GCP project ID to deploy to'
    required: true
  region:
    description: 'GCP region to deploy to'
    required: true
  adk_parameters:
    description: 'Additional parameters for ADK'
runs:
  using: 'docker'
  image: 'Dockerfile'
